#include <iostream>
#include <windows.h> 

int main()
{
while (true) 
{                                             // 16 * 8
std::cout << "     ######     " << std::endl; // **#############
std::cout << "  ##        ##  " << std::endl; // ##**############
std::cout << " #            # " << std::endl; // ####**##########
std::cout << "#              #" << std::endl; // ######**########
std::cout << "#              #" << std::endl; // ########**######
std::cout << " #            # " << std::endl; // ##########**####
std::cout << "  ##        ##  " << std::endl; // ############**##
std::cout << "     ######     " << std::endl; // ##############**
Sleep(8);
system("cls");
std::cout << "*    ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "**   ######     " << std::endl; 
std::cout << "  *#        ##  " << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "**   ######     " << std::endl; 
std::cout << "  **        ##  " << std::endl; 
std::cout << " #  *         # " << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "**   ######     " << std::endl; 
std::cout << "  **        ##  " << std::endl; 
std::cout << " #  **        # " << std::endl; 
std::cout << "#     *        #" << std::endl; 
std::cout << "#              #" << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  **        ##  " << std::endl; 
std::cout << " #  **        # " << std::endl; 
std::cout << "#     **       #" << std::endl; 
std::cout << "#       *      #" << std::endl; 
std::cout << " #            # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  **        # " << std::endl; 
std::cout << "#     **       #" << std::endl; 
std::cout << "#       **     #" << std::endl; 
std::cout << " #        *   # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     **       #" << std::endl; 
std::cout << "#       **     #" << std::endl; 
std::cout << " #        **  # " << std::endl; 
std::cout << "  ##        *#  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       **     #" << std::endl; 
std::cout << " #        **  # " << std::endl; 
std::cout << "  ##        **  " << std::endl; 
std::cout << "     ######   * " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        **  # " << std::endl; 
std::cout << "  ##        **  " << std::endl; 
std::cout << "     ######   **" << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << "  ##        **  " << std::endl; 
std::cout << "     ######   **" << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######   **" << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     ######     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "     #          " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << " #  ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << " #          ##  " << std::endl; 
std::cout << "  ##        ##  " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "#     ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << " #        ##  # " << std::endl; 
std::cout << " #         ###  " << std::endl; 
std::cout << " #        #     " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "      ##       #" << std::endl; 
std::cout << "#       ##     #" << std::endl; 
std::cout << "#         ##  # " << std::endl; 
std::cout << " #          ##  " << std::endl; 
std::cout << " #              " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "      ##       #" << std::endl; 
std::cout << "        ##     #" << std::endl; 
std::cout << "#         ##  # " << std::endl; 
std::cout << "#           ##  " << std::endl; 
std::cout << " #              " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "      ##       #" << std::endl; 
std::cout << "        ##     #" << std::endl; 
std::cout << "          ##  # " << std::endl; 
std::cout << "#           ##  " << std::endl; 
std::cout << "#               " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "      ##       #" << std::endl; 
std::cout << "        ##     #" << std::endl; 
std::cout << "          ##  # " << std::endl; 
std::cout << "            ##  " << std::endl; 
std::cout << "#               " << std::endl;
Sleep(8);
system("cls");
std::cout << "     ######     " << std::endl; 
std::cout << "  ##        ##  " << std::endl; 
std::cout << "    ##        # " << std::endl; 
std::cout << "      ##       #" << std::endl; 
std::cout << "        ##     #" << std::endl; 
std::cout << "          ##  # " << std::endl; 
std::cout << "            ##  " << std::endl; 
std::cout << "                " << std::endl;
Sleep(8);
break;
};
};
